[tool.ruff]
select = [
    "E",
    "F",
    "W",
    "B",
    "I",
    "UP",
    "N",
    # "ANN",
    # "A",
    "C4",
    "PT",
    "SIM",
    "TID",
]
target-version = "py38"

[tool.ruff.isort]
force-single-line = true

[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]

[tool.setuptools_scm]
write_to = "todoman/version.py"
version_scheme = "post-release"

[tool.mypy]
ignore_missing_imports = true
# See https://github.com/python/mypy/issues/7511:
warn_no_return = false

[tool.pytest.ini_options]
testpaths = "tests"
addopts = "--cov=todoman --cov-report=term-missing --color=yes --verbose"
